// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Commands2.proto

#include "Commands2.pb.h"
#include "Commands2.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Interop {
namespace network2 {

static const char* Requester2_method_names[] = {
  "/Interop.network2.Requester2/GetData",
};

std::unique_ptr< Requester2::Stub> Requester2::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Requester2::Stub> stub(new Requester2::Stub(channel));
  return stub;
}

Requester2::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetData_(Requester2_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Requester2::Stub::GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::Interop::network2::CommandReply2* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Interop::network2::CommandRequest2, ::Interop::network2::CommandReply2, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetData_, context, request, response);
}

void Requester2::Stub::experimental_async::GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Interop::network2::CommandRequest2, ::Interop::network2::CommandReply2, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetData_, context, request, response, std::move(f));
}

void Requester2::Stub::experimental_async::GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Interop::network2::CommandReply2>* Requester2::Stub::PrepareAsyncGetDataRaw(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Interop::network2::CommandReply2, ::Interop::network2::CommandRequest2, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Interop::network2::CommandReply2>* Requester2::Stub::AsyncGetDataRaw(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

Requester2::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Requester2_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Requester2::Service, ::Interop::network2::CommandRequest2, ::Interop::network2::CommandReply2, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Requester2::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Interop::network2::CommandRequest2* req,
             ::Interop::network2::CommandReply2* resp) {
               return service->GetData(ctx, req, resp);
             }, this)));
}

Requester2::Service::~Service() {
}

::grpc::Status Requester2::Service::GetData(::grpc::ServerContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Interop
}  // namespace network2

