// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Commands2.proto
#ifndef GRPC_Commands2_2eproto__INCLUDED
#define GRPC_Commands2_2eproto__INCLUDED

#include "Commands2.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace Interop {
namespace network2 {

class Requester2 final {
 public:
  static constexpr char const* service_full_name() {
    return "Interop.network2.Requester2";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::Interop::network2::CommandReply2* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Interop::network2::CommandReply2>> AsyncGetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Interop::network2::CommandReply2>>(AsyncGetDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Interop::network2::CommandReply2>> PrepareAsyncGetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Interop::network2::CommandReply2>>(PrepareAsyncGetDataRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Interop::network2::CommandReply2>* AsyncGetDataRaw(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Interop::network2::CommandReply2>* PrepareAsyncGetDataRaw(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::Interop::network2::CommandReply2* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Interop::network2::CommandReply2>> AsyncGetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Interop::network2::CommandReply2>>(AsyncGetDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Interop::network2::CommandReply2>> PrepareAsyncGetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Interop::network2::CommandReply2>>(PrepareAsyncGetDataRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetData(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Interop::network2::CommandReply2>* AsyncGetDataRaw(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Interop::network2::CommandReply2>* PrepareAsyncGetDataRaw(::grpc::ClientContext* context, const ::Interop::network2::CommandRequest2& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetData(::grpc::ServerContext* context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetData(::grpc::ServerContext* /*context*/, const ::Interop::network2::CommandRequest2* /*request*/, ::Interop::network2::CommandReply2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetData(::grpc::ServerContext* context, ::Interop::network2::CommandRequest2* request, ::grpc::ServerAsyncResponseWriter< ::Interop::network2::CommandReply2>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetData<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetData() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Interop::network2::CommandRequest2, ::Interop::network2::CommandReply2>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::Interop::network2::CommandRequest2* request, ::Interop::network2::CommandReply2* response) { return this->GetData(context, request, response); }));}
    void SetMessageAllocatorFor_GetData(
        ::grpc::experimental::MessageAllocator< ::Interop::network2::CommandRequest2, ::Interop::network2::CommandReply2>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Interop::network2::CommandRequest2, ::Interop::network2::CommandReply2>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetData(::grpc::ServerContext* /*context*/, const ::Interop::network2::CommandRequest2* /*request*/, ::Interop::network2::CommandReply2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetData(
      ::grpc::CallbackServerContext* /*context*/, const ::Interop::network2::CommandRequest2* /*request*/, ::Interop::network2::CommandReply2* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetData(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::Interop::network2::CommandRequest2* /*request*/, ::Interop::network2::CommandReply2* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetData<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetData<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetData(::grpc::ServerContext* /*context*/, const ::Interop::network2::CommandRequest2* /*request*/, ::Interop::network2::CommandReply2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetData(::grpc::ServerContext* /*context*/, const ::Interop::network2::CommandRequest2* /*request*/, ::Interop::network2::CommandReply2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetData() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetData(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetData(::grpc::ServerContext* /*context*/, const ::Interop::network2::CommandRequest2* /*request*/, ::Interop::network2::CommandReply2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetData(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Interop::network2::CommandRequest2, ::Interop::network2::CommandReply2>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Interop::network2::CommandRequest2, ::Interop::network2::CommandReply2>* streamer) {
                       return this->StreamedGetData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetData(::grpc::ServerContext* /*context*/, const ::Interop::network2::CommandRequest2* /*request*/, ::Interop::network2::CommandReply2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Interop::network2::CommandRequest2,::Interop::network2::CommandReply2>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetData<Service > StreamedService;
};

}  // namespace network2
}  // namespace Interop


#endif  // GRPC_Commands2_2eproto__INCLUDED
